### ISSUE TITLE
Weekday one day behind

### ISSUE THREAD

**Issue by viegelinsch** [tubraunschweig/duely#1]
The calendar of duels shows the dates all one weekday to late.
Example: 07th November 2017 is a "Monday" for duely but a "Tuesday" in reality.
This error appear in the web as on the desktop.

Consequence or coincidence: The import of created appointments leads to daily appointments although they should have been weekly.

**Comment by rukichen** [comment]
Changed Weekstart in to Monday. One day behind is fixed, too, with commit 4b2c5bd9029828548dcd96e32022cb44b53649d3
